services:
  api:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    image: fastapi-torch:${tag:-latest}
    container_name: fast-api
    ports:
      - "5005:5005"
    command: uvicorn run:app --host 0.0.0.0 --port 33361
    restart: unless-stopped  # 이 부분을 추가하여 자동 재시작을 설정하세요


networks:
  traefik:
    external: true
